# Generated by Django 4.0.6 on 2022-07-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_models_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='skip',
            field=models.BooleanField(default=True),
        )
    ]
