# Generated by Django 4.0.6 on 2022-07-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_office', '0011_models_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'sent'), (1, 'failed'), (2, 'queued'), (3, 'requeued'), (4, 'skipped')], db_index=True, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='log',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'sent'), (1, 'failed'), (4, 'skipped')], verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='emailtemplate',
            name='skip',
            field=models.BooleanField(default=False),
        ),
    ]
